AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nlpjs-lambda

  Sample SAM Template for nlpjs-lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorld2Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello2
            Method: get
  NLPjsDyDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nlpjs/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: NLPjsModelTable
      Environment:
        Variables:
          MODEL_TABLENAME:
            Ref: NLPjsModelTable
      Events:
        NLPjs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /talkDyDB
            Method: any
  NLPjsModelTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: "id"
        Type: "String"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorld2Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World 2 function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello2/"
  HelloWorld2Function:
    Description: "Hello World 2 Lambda Function ARN"
    Value: !GetAtt HelloWorld2Function.Arn
  HelloWorld2FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World 2 function"
    Value: !GetAtt HelloWorld2FunctionRole.Arn
  NLPjsDyDBApi:
    Description: "API Gateway endpoint URL for Prod stage for NLPjs-DyDB function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/talkDyDB/"
  NLPjsDyDBFunction:
    Description: "NLPjs-DyDB Lambda Function ARN"
    Value: !GetAtt NLPjsDyDBFunction.Arn
  NLPjsDyDBFunctionIamRole:
    Description: "Implicit IAM Role created for NLPjs-DyDB function"
    Value: !GetAtt NLPjsDyDBFunctionRole.Arn
